CREATE TABLE events(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    start_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    duration TINYINT,
    end_date DATETIME
);